---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: ci-intel-dgpu-driver-container-kmmo
  name: ci-intel-dgpu-driver-container-kmmo
  namespace: intel-dgpu
spec: {}

---
apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: ci-intel-dgpu-cicd-build-mode
  namespace: intel-dgpu
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: i915
        firmwarePath: /i915
      kernelMappings:
        - regexp: ^.*\.x86_64$
          containerImage: image-registry.openshift-image-registry.svc:5000/intel-dgpu/ci-intel-dgpu-driver-container-kmmo:$KERNEL_FULL_VERSION
          pull:
            insecureSkipTLSVerify: true
          build:
            pull:
              insecureSkipTLSVerify: true
              insecure: false
            push:
              insecureSkipTLSVerify: true
              insecure: false
            dockerfileConfigMap:
              name: ci-intel-dgpu-dockerfile-configmap
  selector:
    intel.feature.node.kubernetes.io/gpu: "true"
    intel.feature.node.kubernetes.io/dgpu-canary: "true"
